# Generated by Django 4.1.7 on 2024-04-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='game',
            name='cover_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='icon_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
